Changing card dynamics
luisotavio756/d-learn pull request #14
Opened 2024-03-25 11:57 UTC by mateusxfl

The dynamics of the lucky or unlucky cards were changed, as well as new cards were added and their layout was also changed.

2024-03-25 16:14 UTC, mateusxfl commented on src/contexts/game.context.tsx
> +    if (player.customLuckAction === undefined) return;
Na verdade não, pois no caso onde customLuckAction seja o primeiro valor do enum (0) a condição será true, e dessa forma estaria errado pois haveria uma customLuckAction no jogador e nao seria removido.

2024-03-25 16:16 UTC, mateusxfl commented on src/contexts/game.context.tsx
> +      if (card.luckAction === undefined) return;
Na verdade não, pois no caso onde luckAction seja o primeiro valor do enum (0) a condição será true, e dessa forma estaria errado pois haveria uma luckAction na carta e nao seria cadastrado no jogador.

2024-03-26 02:00 UTC, luisotavio756 requested changes

2024-03-26 02:00 UTC, luisotavio756 commented on src/contexts/game.context.tsx
> +    (answeredCorrectly?: boolean) => {
tu não resolveu esse amigo

2024-03-26 13:37 UTC, mateusxfl commented on src/contexts/game.context.tsx
> +    (answeredCorrectly?: boolean) => {
Done ✅

2024-03-26 20:00 UTC, merged